"""introduce chat_sessions and reshape chat_messages

Revision ID: 4e84f6c9a28f
Revises: 7111aeb1057f
Create Date: 2025-08-09 02:33:35.067776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e84f6c9a28f'
down_revision: Union[str, Sequence[str], None] = '7111aeb1057f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_character_id'), 'chat_sessions', ['character_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.add_column('chat_messages', sa.Column('session_id', sa.Integer(), nullable=False))
    op.add_column('chat_messages', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_chat_messages_character_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_uid'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_user'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_constraint(op.f('chat_messages_character_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.drop_column('chat_messages', 'session_uid')
    op.drop_column('chat_messages', 'user')
    op.drop_column('chat_messages', 'character_id')
    op.drop_column('chat_messages', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('user', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('session_uid', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_character_id_fkey'), 'chat_messages', 'characters', ['character_id'], ['id'])
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_user'), 'chat_messages', ['user'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_uid'), 'chat_messages', ['session_uid'], unique=False)
    op.create_index(op.f('ix_chat_messages_character_id'), 'chat_messages', ['character_id'], unique=False)
    op.drop_column('chat_messages', 'timestamp')
    op.drop_column('chat_messages', 'session_id')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_character_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
