"""expand_characters_table_universal_schema

Revision ID: 66e7609b7cb9
Revises: 9897dd37e71e
Create Date: 2025-07-31 06:49:44.363499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e7609b7cb9'
down_revision: Union[str, Sequence[str], None] = '9897dd37e71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('character_type', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('characters', sa.Column('rating', sa.String(length=20), nullable=True))
    op.add_column('characters', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('characters', sa.Column('max_tokens', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('temperature', sa.String(length=10), nullable=True))
    op.add_column('characters', sa.Column('top_p', sa.String(length=10), nullable=True))
    op.add_column('characters', sa.Column('usage_count', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('avg_rating', sa.String(length=10), nullable=True))
    op.add_column('characters', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('characters', sa.Column('is_active', sa.String(length=10), nullable=True))
    op.add_column('characters', sa.Column('is_public', sa.String(length=10), nullable=True))
    op.add_column('characters', sa.Column('version', sa.String(length=20), nullable=True))
    op.add_column('characters', sa.Column('source_file', sa.String(length=200), nullable=True))
    op.add_column('characters', sa.Column('custom_fields', sa.JSON(), nullable=True))
    op.alter_column('characters', 'personality',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('characters', 'background',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('characters', 'speaking_style',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('characters', 'mood',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('characters', 'voice',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.alter_column('characters', 'voice',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('characters', 'mood',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('characters', 'speaking_style',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('characters', 'background',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('characters', 'personality',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('characters', 'custom_fields')
    op.drop_column('characters', 'source_file')
    op.drop_column('characters', 'version')
    op.drop_column('characters', 'is_public')
    op.drop_column('characters', 'is_active')
    op.drop_column('characters', 'last_used_at')
    op.drop_column('characters', 'avg_rating')
    op.drop_column('characters', 'usage_count')
    op.drop_column('characters', 'top_p')
    op.drop_column('characters', 'temperature')
    op.drop_column('characters', 'max_tokens')
    op.drop_column('characters', 'language')
    op.drop_column('characters', 'rating')
    op.drop_column('characters', 'tags')
    op.drop_column('characters', 'character_type')
    # ### end Alembic commands ###
